# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.0
  - 7.1
  - 7.2
  - hhvm

script: phpunit --configuration tests/phpunit.xml

