# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.2
  - 7.3
  - 7.4

install:
   - cd tests && composer install

script: phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 
